server:
  port: 8081
spring:
  application:
    name: my-app
  datasource:
    url: jdbc:mariadb://localhost:3306/loanSystem
    username: root
    password: Password@1
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'    
security:
  user:
    name: admin
    password: admin
    
